language: python
python:
- 2.7
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- git clone https://github.com/plone/plone.themepreview ../themepreview
- cd ../themepreview
- mkdir -p buildout-cache/downloads build/html
- python bootstrap.py -c travis.cfg
- bin/buildout -c travis.cfg
  buildout:develop=../plonetheme.bootstrap
  sources:collective.js.bootstrap="git https://github.com/collective/collective.js.bootstrap"
  buildout:auto-checkout=collective.js.bootstrap
  buildout:eggs=plonetheme.bootstrap
  versions:plone.app.jquery=1.8.3
before_script:
- gem install --version 0.8.9 faraday
- gem install travis-artifacts
script:
- bin/sphinx-build -b html source build/html
after_script:
- travis-artifacts upload --path build/html
- travis-artifacts upload --target-path latest --path build/html
env:
  global:
  - ARTIFACTS_S3_BUCKET=plonetheme-bootstrap
  - SPHINX_PROJECT=plonetheme.bootstrap
  - SPHINX_COPYRIGHT=Collective
  - ROBOT_CONFIGURE_PACKAGES=plonetheme.bootstrap
  - ROBOT_APPLY_PROFILES=plone.app.theming:default,plonetheme.bootstrap:default
  - secure: f31GHIEGGrtIIdEy7JAHG/gCwazqGLpDcHxnHX8eaj/V9VSbc2gSKk2GFSNHyOyyvR+OCwPd3J7QDTntpGbihOld5dBb6Cy+9zDd/Rpd3FTsjIsVDta2YXDVc3R7Znrah7DFjv8lLZ+7EDZ7rKbvODZRAAFuDcAZ9yD/Kt8b+vk=
  - secure: qBt2U1vm0dytn1n7rzcsK8y1S+QU34hHSW+2YZehDerRyMgy1T/quVwDeq1o4kP7MRRplUxATT16jTBx8B8oFgjQ89UQsQlLvzcH5uMWalhn2x+X0fmn+bR7QfvSMfeMaicwLVZ5+qDUfNw7VS8w2Dj62E/t5h7bKfOr49HMyZs=
notifications:
  irc:
    channels:
    - irc.freenode.org#plone-docs
    template:
    - ! '%{repository}#%{build_number} (%{branch} | %{commit} | %{author}): %{message}'
    - ! 'Sphinx: http://plonetheme-bootstrap.s3-website-us-east-1.amazonaws.com/artifacts/%{build_number}/%{build_number}.1/'
